services:
  banco-dados:
    image: postgres:15-alpine
    container_name: banco_dados_container
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: sistema_pedidos
    networks:
      - rede-arquitetura
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sistema_pedidos"]
      interval: 5s
      timeout: 5s
      retries: 10

  produto-service:
    build: ./produto-service
    container_name: produto_service_container
    ports:
      - "8002:8000"
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://postgres:senha@banco-dados:5432/sistema_pedidos
    networks:
      - rede-arquitetura
    depends_on:
      banco-dados:
        condition: service_healthy

  restaurante-service:
    build: ./restaurante-service
    container_name: restaurante_service_container
    ports:
      - "8003:8000"
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://postgres:senha@banco-dados:5432/sistema_pedidos
    networks:
      - rede-arquitetura
    depends_on:
      banco-dados:
        condition: service_healthy

  cliente-service:
    build: ./cliente-service
    container_name: cliente_service_container
    ports:
      - "8004:8000"
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://postgres:senha@banco-dados:5432/sistema_pedidos
    networks:
      - rede-arquitetura
    depends_on:
      banco-dados:
        condition: service_healthy

  pedido-service:
    build: ./pedido-service
    container_name: pedido_service_container
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://banco-dados:5432/sistema_pedidos
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=senha
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - URL_CLIENTE=http://cliente-service:8000
      - URL_RESTAURANTE=http://restaurante-service:8000
      - URL_PRODUTO=http://produto-service:8000
    depends_on:
      banco-dados:
        condition: service_healthy
      produto-service:
        condition: service_started
      restaurante-service:
        condition: service_started
      cliente-service:
        condition: service_started
    networks:
      - rede-arquitetura

networks:
  rede-arquitetura:
    driver: bridge

volumes:
  postgres_data: